name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main  # Укажите ветку, которую хотите деплоить

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Yandex Cloud
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.250.24.175 "
            cd /var/www/my-chat-backend &&
            git fetch --all &&
            git reset --hard origin/main &&
            npm install &&
            pm2 restart my-chat-backend
          "