name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main  # или другая ветка, на которую хотите настроить деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # укажите нужную версию Node.js

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        run: |
          ssh username@your_vm_ip "cd my-chat-backend && git pull && yarn install && pm2 restart my-app"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY1 }}  # добавьте ваш ключ в Secrets
          YOUR_VM_IP: ${{ secrets.YOUR_VM_IP }}  # добавьте IP адрес в Secrets